repos:
  - repo: https://github.com/b-/tf-pre-commit
    rev: v0.1.30
    hooks:
      - id: terraform-fmt
      #- id: terraform-validate
      - id: tflint
      - id: shellcheck
      - id: gofmt
      - id: golint

